# © 2020 Joseph Cameron - All Rights Reserved
# jfc-travis_ci_canary ci script

dist: bionic 
sudo: required
language: cpp

matrix:
  include:
    # Build scripts
    - os: linux
      name: build linux gcc
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - git
            - libgtk-3-dev
            - curl
      script:
        - |
          cd workspace
          cmake .. -DJFC_BUILD_DOCS=OFF -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Ofast -flto -funroll-loops -m64 -march=native -Wno-deprecated-declarations"
          make
          ctest --extra-verbose

    - os: linux
      dist: bionic 
      arch: arm64
      name: build linux gcc
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - git
            - libgtk-3-dev
            - curl
      script:
        - |
          cd workspace
          cmake .. -DJFC_BUILD_DOCS=OFF -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Ofast -flto -funroll-loops -m64 -march=native -Wno-deprecated-declarations"
          make
          ctest --extra-verbose

    - os: osx
      name: build macos clang
      osx_image: xcode12.2
      compiler: clang
      addons:
        homebrew:
          packages:
            - gtk+3
            - gtk-3
      script:
        - |
          cd workspace
          cmake .. -DJFC_BUILD_DOCS=OFF -DCMAKE_CXX_FLAGS="-std=c++17 -stdlib=libc++"
          #cmake .. -DJFC_BUILD_DOCS=OFF -DCMAKE_CXX_FLAGS="-pedantic -Weverything -Wno-c++98-compat -Wno-padded -Ofast -flto -funroll-loops -m64 -march=native -std=c++17 -stdlib=libc++"
          make
          ctest --extra-verbose

#    - os: windows
#      name: build windows msvc
#      compiler: MSVC
#      script: 
#        - |
#          cd workspace
#          cmake .. -DJFC_BUILD_DOCS=OFF #-DCMAKE_CXX_FLAGS=" /W4 /EHsc /WX /std:c++17 /permissive-"
#          cmake --build .

#    - os: windows
#      name: build windows mingw
#      compiler: mingw64
#      install: choco install mingw
#      script: 
#        - |
#          cd workspace
#          cmake .. -G "MinGW Makefiles" -DJFC_BUILD_DOCS=OFF -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Ofast -flto -funroll-loops -m64 -march=native"
#          cmake --build .

before_script: 
  - |
    CURRENT_COMMIT_HASH="$(git rev-parse HEAD)"
